### ISSUE TITLE
Parser doesn't like PROGRAM-ID attribute

### ISSUE THREAD

**Issue by yngwietiger** [carlanton/m3u8-parser#1]
Hi, 

I'm generating manifests via AWS Elastic Transcoder, and they come with PROGRAM-ID:

#EXT-X-I-FRAME-STREAM-INF:**PROGRAM-ID=1**,BANDWIDTH=29971000,CODECS="avc1.4d001f",URI="output/2M_iframe.m3u8"

But when I try to parse, I get:

io.lindstrom.m3u8.parser.PlaylistParserException: Unknown key PROGRAM-ID
	at io.lindstrom.m3u8.parser.IFrameParser.parseAttributes(IFrameParser.java:43)
	at io.lindstrom.m3u8.parser.IFrameParser.parseAttributes(IFrameParser.java:9)
	at io.lindstrom.m3u8.parser.AbstractLineParser.parse(AbstractLineParser.java:33)
	at io.lindstrom.m3u8.parser.AbstractLineParser.parse(AbstractLineParser.java:24)
	at io.lindstrom.m3u8.parser.MasterPlaylistParser.onTag(MasterPlaylistParser.java:65)
	at io.lindstrom.m3u8.parser.MasterPlaylistParser.onTag(MasterPlaylistParser.java:34)
	at io.lindstrom.m3u8.parser.AbstractPlaylistParser.readPlaylist(AbstractPlaylistParser.java:93)
	at io.lindstrom.m3u8.parser.AbstractPlaylistParser.readPlaylist(AbstractPlaylistParser.java:59)
	at io.lindstrom.m3u8.parser.AbstractPlaylistParser.readPlaylist(AbstractPlaylistParser.java:19)

Thanks.

**Comment by carlanton** [comment]
Hi @yngwietiger,

The PROGRAM-ID tag was actually removed from the HLS spec 5 years ago. Interesting that Amazon still uses it :)
Anyhow, I just added support for the tag in version 0.6 of this library. It should be available via maven within an hour. Please give it a try and see if it fixes your issue!

**Comment by yngwietiger** [comment]
Yep. I see that it was removed in v6. Amazon generates in v3 or v4 (user's choice), nothing beyond that though. 

Thanks for the change! I'll take a look.
