### ISSUE TITLE
#EXT-X-BITRATE not implemented.

### ISSUE THREAD

**Issue by open-leocat** [carlanton/m3u8-parser#22]
Hi. You have said that the Tag #EXT-X-BITRATE is supported but it isn't. Here is my java error:
```
io.lindstrom.m3u8.parser.PlaylistParserException: Tag not implemented: #EXT-X-BITRATE
	at io.lindstrom.m3u8.parser.MediaPlaylistParser.onTag(MediaPlaylistParser.java:128)
	at io.lindstrom.m3u8.parser.MediaPlaylistParser.onTag(MediaPlaylistParser.java:38)
	at io.lindstrom.m3u8.parser.AbstractPlaylistParser.readPlaylist(AbstractPlaylistParser.java:95)
	at io.lindstrom.m3u8.parser.AbstractPlaylistParser.readPlaylist(AbstractPlaylistParser.java:61)
	at io.lindstrom.m3u8.parser.AbstractPlaylistParser.readPlaylist(AbstractPlaylistParser.java:21)
```
Here is my m3u8 file:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-TARGETDURATION:10
#EXT-X-MEDIA-SEQUENCE:55119
#EXT-X-PROGRAM-DATE-TIME:2020-07-21T08:14:29.379Z
#EXT-X-BITRATE:1674
#EXTINF:9.600,
test1.ts
#EXT-X-BITRATE:1625
#EXTINF:9.600,
test2.ts
#EXT-X-BITRATE:1679
#EXTINF:9.600,
test3.ts
#EXT-X-BITRATE:1590
#EXTINF:9.600,
test4.ts
#EXT-X-BITRATE:1641
#EXTINF:9.600,
test5.ts
#EXT-X-BITRATE:1648
#EXTINF:9.600,
test6.ts
#EXT-X-BITRATE:1670
#EXTINF:9.600,
test7.ts
#EXT-X-BITRATE:1683
#EXTINF:9.600,
test8.ts
#EXT-X-BITRATE:1594
#EXTINF:9.600,
test9.ts
#EXT-X-BITRATE:1639
#EXTINF:9.600,
test10.ts
```
Thanks in advance!

**Comment by carlanton** [comment]
Are you using version 0.14?

**Comment by open-leocat** [comment]
Oh I have used an old version... that explains it! Thanks
