### ISSUE TITLE
EXT-X-CUE-OUT parsing fails on non-integer data

### ISSUE THREAD

**Issue by swpalmer** [carlanton/m3u8-parser#38]
Occasionally I see the following exception:

     java.lang.NumberFormatException: For input string: "89.990"
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
        at java.base/java.lang.Integer.parseInt(Integer.java:660)
        at java.base/java.lang.Integer.parseInt(Integer.java:778)
        at io.lindstrom.m3u8.parser.MediaSegmentTag$5.read(MediaSegmentTag.java:69)
        at io.lindstrom.m3u8.parser.MediaSegmentTag$5.read(MediaSegmentTag.java:66)
        at io.lindstrom.m3u8.parser.MediaPlaylistParser.onTag(MediaPlaylistParser.java:53)
        at io.lindstrom.m3u8.parser.MediaPlaylistParser.onTag(MediaPlaylistParser.java:32)
        at io.lindstrom.m3u8.parser.AbstractPlaylistParser.readPlaylist(AbstractPlaylistParser.java:92)
        at io.lindstrom.m3u8.parser.AbstractPlaylistParser.readPlaylist(AbstractPlaylistParser.java:58)
        at io.lindstrom.m3u8.parser.AbstractPlaylistParser.readPlaylist(AbstractPlaylistParser.java:18)

See https://docs.aws.amazon.com/medialive/latest/ug/sample-manifests-hls.html

**Comment by carlanton** [comment]
Released in 0.20. Thanks again :)
