### ISSUE TITLE
always NoClassDefFoundError is thrown on Android under api 26

### ISSUE THREAD

**Issue by HiroyukTamura** [carlanton/m3u8-parser#9]
### Reproduce
run `MediaPlaylistParser().readPlaylist(string)` on android that is under api 26

### Stacktrace
 
```
Caused by java.lang.ClassNotFoundException: Didn't find class "java.time.format.DateTimeFormatterBuilder" on path: DexPathList[[zip file "/data/app/${MyPackageName}-1/base.apk", zip file "/data/app/${MyPackageName}-1/split_config.arm64_v8a.apk", zip file "/data/app/${MyPackageName}-1/split_config.ja.apk", zip file "/data/app/${MyPackageName}-1/split_config.xhdpi.apk"],nativeLibraryDirectories=[/data/app/${MyPackageName}-1/lib/arm64, /vendor/lib64, /system/lib64]]
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
       at io.lindstrom.m3u8.parser.MediaPlaylistParser.<clinit>(MediaPlaylistParser.java)
       at be.tramckrijte.workmanager.DownloadClient$requestMediaPlaylist$1.onFailure(DownloadClient.java)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.java)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:831)
```

this is because some Java 8 APIs(ex. `java.time.*`) [isn't supported under android api level 26](https://developer.android.com/studio/write/java8-support?hl=ja#supported_features). 

So when running code on android that is older than 26, we must apply [core library desugaring](https://developer.android.com/studio/preview/features#j8-desugar) to the app.
I think it's worth to append that to the readme file.

**Comment by carlanton** [comment]
Thanks for the report! Do you have any idea of how to approach this problem?
-- 
Mvh Anton Sent from my iPhone
